Make the wait-for-port timeout adjustable
bitnami/bitnami-docker-influxdb pull request #9
Opened 2022-01-26 09:38 UTC by dshmatov

**Description of the change**

Added the `wait-for-port` timeout and made it adjustable.

**Benefits**

Sometimes it is mandatory to set this timeout, especially when the huge amount of data is already in the influx and it tries to start but fails due to default 30s timeout. Therefore it's pretty reasonable to make it adjustable.

**Possible drawbacks**

Don't see any

**Applicable issues**

- https://github.com/bitnami/charts/issues/5182
- https://github.com/influxdata/influxdb/issues/19849
- https://github.com/bitnami/charts/issues/5519

2022-01-27 08:50 UTC, miguelaeh requested changes
tank you for the PR please take a look to the suggested changes

2022-01-27 08:50 UTC, miguelaeh commented on 1/debian-10/rootfs/opt/bitnami/scripts/libinfluxdb.sh
> +    [[ "${branch}" = "1" ]] && wait-for-port --timeout=$INFLUXDB_PORT_READINESS_TIMEOUT "$INFLUXDB_PORT_NUMBER"
```suggestion
    [[ "${branch}" = "1" ]] && wait-for-port --timeout="$INFLUXDB_PORT_READINESS_TIMEOUT" "$INFLUXDB_PORT_NUMBER"
```

2022-01-27 08:50 UTC, miguelaeh commented on 1/debian-10/rootfs/opt/bitnami/scripts/libinfluxdb.sh
> +    [[ "${branch}" = "1" ]] && wait-for-port --timeout=$INFLUXDB_PORT_READINESS_TIMEOUT "$INFLUXDB_PORT_NUMBER"
Please apply this change to all the uses of the variable

2022-01-27 09:59 UTC, dshmatov commented
@miguelaeh please check one, added quotes

2022-01-27 09:59 UTC, dshmatov commented on 1/debian-10/rootfs/opt/bitnami/scripts/libinfluxdb.sh
> +    [[ "${branch}" = "1" ]] && wait-for-port --timeout=$INFLUXDB_PORT_READINESS_TIMEOUT "$INFLUXDB_PORT_NUMBER"
Ok, I'll do

2022-01-28 09:31 UTC, miguelaeh approved these changes
LGTM!

2022-01-28 09:32 UTC, merged